#!/bin/bash

ROOTFS_PATH=${1}


echo '
Section "Device"
    Identifier  "i.MX Accelerated Framebuffer Device"
    Driver      "vivante"
    Option      "fbdev"     "/dev/fb0"
    Option      "vivante_fbdev" "/dev/fb0"
    Option      "HWcursor"  "false"
EndSection

Section "ServerFlags"
    Option "BlankTime"  "0"
    Option "StandbyTime"  "0"
    Option "SuspendTime"  "0"
    Option "OffTime"  "0"
EndSection
' >> ${ROOTFS_PATH}/etc/X11/xorg.conf

# echo '
# Section "Device"
#         Identifier      "Generic Video Card"
#         Driver          "fbdev"
#         Option          "Rotate"             "off"
# EndSection

# Section "Monitor"
#         Identifier      "Generic Monitor"
# EndSection

# Section "Screen"
#         Identifier      "Default Screen"
#         Device          "Generic Video Card"
#         Monitor         "Generic Monitor"
#         DefaultDepth    24
#         SubSection      "Display"
#         Depth           24
#         Modes           "800x480"
#         EndSubSection
# EndSection

# # Section "InputDevice"
# #     Identifier        "Pointer"
# #     Driver            "tslib"
# #     Option            "Device"             "/dev/input/touchscreen0"
# #     Option            "CorePointer"        "true"
# #     Option            "SendCoreEvents"     "true"
# # EndSection

# # Section "InputDevice"
# #         Identifier    "Keyboard"
# #         Driver        "kbd"
# # EndSection

# Section "ServerLayout"
#         Identifier      "Default Layout"
#         Screen          "Default Screen"
#         InputDevice     "Pointer"
#         InputDevice     "Keyboard"
# EndSection
# ' >> ${ROOTFS_PATH}/etc/X11/xorg.conf
