#!/bin/bash

exit 0

echo $0

echo "
[Service]
ExecStart=
ExecStart=-/usr/bin/agetty --autologin username -s %I 115200,38400,9600 vt102
" >> build/rootfs/etc/systemd/system/serial-getty@ttyS0.service.d/autologin.conf
